-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 04:48:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendor` (
  `ItemVendor` INT NOT NULL,
  `VenderPhone` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `ItemVendor_UNIQUE` (`ItemVendor` ASC) VISIBLE,
  PRIMARY KEY (`ItemVendor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `InvoiceID` INT NOT NULL,
  `InvoiceDate` DATE NOT NULL,
  `InvoicePrice` DOUBLE NULL,
  `InvoiceItem` VARCHAR(45) NULL,
  PRIMARY KEY (`InvoiceID`),
  UNIQUE INDEX `InvoiceID_UNIQUE` (`InvoiceID` ASC) VISIBLE,
  CONSTRAINT `ItemVendor`
    FOREIGN KEY (`InvoiceID`)
    REFERENCES `mydb`.`Vendor` (`ItemVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buyer` (
  `BuyerID` INT NOT NULL,
  `BuyerLasName` VARCHAR(45) NOT NULL,
  `BuyerFirstName` VARCHAR(45) NOT NULL,
  `BuyerPhone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BuyerID`),
  UNIQUE INDEX `BuyerID_UNIQUE` (`BuyerID` ASC) VISIBLE,
  CONSTRAINT `InvoiceItem`
    FOREIGN KEY (`BuyerID`)
    REFERENCES `mydb`.`Invoice` (`InvoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Invoice`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (1, '7/14/2013', 3,000.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (2, '7/14/2013', 1,200.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (3, '7/14/2013', 800.00, 'I Love lamps');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (4, '7/14/2013', 45.00, 'I Heart Candles');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (5, '7/14/2013', 250.00, 'PutUrbooksHere.com');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (6, '7/16/2013', 25,000.00, 'Tables And More');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (7, '8/12/2013', 200.00, 'PutUrbooksHere.com');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (8, '8/12/2013', 1,000.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (9, '8/24/2013', 1,000.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (10, '8/25/2013', 4,500.00, 'Couches A Plenty');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (11, '9/1/2013', 500.00, 'PutUrbooksHere.com');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (12, '9/2/2013', 1250.00, 'Chest-R-Us');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (13, '9/2/2013', 75.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (14, '9/2/2013', 125.00, 'Chairs, Chairs, Chairs');
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (, DEFAULT, NULL, NULL);
INSERT INTO `mydb`.`Invoice` (`InvoiceID`, `InvoiceDate`, `InvoicePrice`, `InvoiceItem`) VALUES (, DEFAULT, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Buyer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (, '', '', '');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (1, 'Shire', 'Robert', '205-555-5523');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (1, 'Shire', 'Robert', '205-555-5523');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (1, 'Shire', 'Robert', '205-555-5523');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (2, 'Bancroft', 'Chris', '201-555-5512');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (2, 'Bancroft', 'Chris', '201-555-5512');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (1, 'Shire', 'Robert', '205-555-5523');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (3, 'Smith', 'Robert', '204-123-1234');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (3, 'Smith', 'Robert', '204-123-1235');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (3, 'Smith', 'Robert', '204-123-1236');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (4, 'Goodyear', 'Katherine', '123-555-1234');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (1, 'Shire', 'Robert', '205-555-5523');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (4, 'Goodyear', 'Katherine', '123-555-1234');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (4, 'Goodyear', 'Katherine', '123-555-1234');
INSERT INTO `mydb`.`Buyer` (`BuyerID`, `BuyerLasName`, `BuyerFirstName`, `BuyerPhone`) VALUES (4, 'Goodyear', 'Katherine', '123-555-1234');

COMMIT;

